//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub guild_id: Option<String>,
    pub color: i32,
    pub hoist: bool,
    pub managed: bool,
    pub mentionable: bool,
    pub name: String,
    pub permissions: String,
    pub position: i32,
    pub icon: Option<String>,
    pub unicode_emoji: Option<String>,
    pub tags: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::guilds::Entity",
        from = "Column::GuildId",
        to = "super::guilds::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Guilds,
}

impl Related<super::guilds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Guilds.def()
    }
}

impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        super::message_role_mentions::Relation::Messages.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::message_role_mentions::Relation::Roles.def().rev())
    }
}

impl Related<super::members::Entity> for Entity {
    fn to() -> RelationDef {
        super::member_roles::Relation::Members.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::member_roles::Relation::Roles.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
