//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sticker_packs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub description: Option<String>,
    pub banner_asset_id: Option<String>,
    pub cover_sticker_id: Option<String>,
    #[sea_orm(column_name = "coverStickerId")]
    // End me, why are there two of these
    pub cover_sticker_id_two: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::stickers::Entity",
        from = "Column::CoverStickerId",
        to = "super::stickers::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Stickers,
}

impl Related<super::stickers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stickers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
